### ISSUE TITLE
Component Position - FeatureRequest

### ISSUE THREAD

**Issue by ImOverlord** [JulienTD/BillyScene#1]
When creating a sprite, you cannot give a z position to a component, this means you can't control on top of what the element is without changing the list of components.

It would be great if it was possible to give a z position to the components when creating it. Or maybe a layer id system so its easy to know on top of what an element is and what's over it.

**Comment by JulienTD** [comment]
This feature was added with commit 221dc01e141e879fb64233801c8db82e479e277e
